services:
  budgetbuddy:
    build: .
    container_name: budgetbuddy_app
    restart: always
    ports:
      - "127.0.0.1:5003:5003" 
    env_file: .env
    environment:
      - PORT=5003
      # Note: We use the container name 'postgres_db' because they share a network
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
    networks:
      - shared_network

networks:
  shared_network:
    external: true
