services:
  budgetbuddy:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: budgetbuddy_app
    restart: always
    ports:
      - "127.0.0.1:5003:5003"
    env_file: .env
    environment:
      - PORT=5003
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
